version: "3.8"

services:
  # PHP Service
  app:
    # Hapus bagian 'build:', kita murni pakai image dari GitHub (GHCR)
    image: ghcr.io/aliffajriadi/batam-campus-expo:latest
    container_name: bce-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./.env:/var/www/.env
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      # - app-data:/var/www
    networks:
      - bce-network

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: bce-web
    restart: unless-stopped
    ports:
      - "8000:80" # Di prod biasanya pakai port 80/443
    volumes:
      # - app-data:/var/www
      # JANGAN MOUNT ./:/var/www (Ini yang bikin CSS rusak & Permission error)
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      # Kita pakai volumes_from agar Nginx bisa baca file statis (CSS/JS) dari container App
      - ./storage/app/public:/var/www/storage/app/public
    networks:
      - bce-network
    depends_on:
      - app

  # Database Service
  db:
    image: mariadb:10.11
    container_name: bce-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-bce}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-root}
    volumes:
      - bce-db-data:/var/lib/mysql
    networks:
      - bce-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: bce-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - bce-redis-data:/data
    networks:
      - bce-network

networks:
  bce-network:
    driver: bridge

volumes:
  bce-db-data:
    driver: local
  bce-redis-data:
    driver: local
  # app-data:
  #   driver: local
